---
- name: Install WordPress, MySQL, Nginx, and PHP-FPM
  hosts: nginx-wordpress
  #remote_user: root
  # remote_user: user
  sudo: yes

  roles:
    - common
    - mysql
    - nginx
    - php-fpm
    - wordpress
